"""
ai_analysis.py — Optional AI-driven analysis step using the Claude API.

Reads all generated artifacts from a completed test run, injects the specs files
as expert context, and calls Claude to produce a narrative expert analysis that
goes beyond the algorithmic comparison: cross-signal reasoning, root cause
hypotheses, and ranked recommendations.

Output: <run_dir>/comparison/final_analysis.md

Requires: ANTHROPIC_API_KEY environment variable.
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

try:
    import anthropic
except ImportError:
    anthropic = None  # type: ignore


MODEL = "claude-opus-4-6"
MAX_TOKENS = 4096

# Specs files read at runtime and injected into the system prompt
SPECS_FILES = [
    "specs/PPROF_ANALYSIS.md",
    "specs/COMPARISON_METHODOLOGY.md",
    "specs/METRICS.md",
]

# Data files fed to the AI as user message content
DATA_FILES = [
    ("comparison/comparison_report.md", "Algorithmic Comparison Report (primary data)"),
    ("comparison/comparison_data.json", "Structured Comparison Data (JSON)"),
    ("cel/analysis/summary.json", "CEL Run — Full Summary"),
    ("akamai/analysis/summary.json", "Akamai Run — Full Summary"),
    ("cel/analysis/pprof_report.txt", "CEL Run — pprof Analysis"),
    ("akamai/analysis/pprof_report.txt", "Akamai Run — pprof Analysis"),
]

OUTPUT_FILENAME = "final_analysis.md"

# ── System prompt ──────────────────────────────────────────────────────────────

SYSTEM_PROMPT_HEADER = """\
You are an expert Filebeat and Go runtime performance analyst specialising in \
Akamai SIEM API integrations. You have deep knowledge of Go's garbage collector, \
profiling tools (pprof), the Filebeat libbeat pipeline architecture, and the \
Akamai SIEM API behaviour (offset-based pagination, HMAC authentication, \
EdgeGrid signing).

Your task: analyse the performance test results comparing Filebeat's CEL input \
against the native Akamai input, and produce an expert narrative analysis in the \
exact markdown format specified at the end of this prompt.

The test ran both inputs sequentially with identical parameters against the same \
Akamai SIEM test API server. Three categories of metrics were collected:
1. Filebeat monitoring logs (counter deltas every 60s — beat, libbeat, pipeline, queue, output)
2. /inputs/ HTTP endpoint snapshots (cumulative counters every 60s — input-specific metrics)
3. pprof profiles (heap baseline, 30s CPU at midpoint, final heap/block/mutex)

---

## Expert Knowledge: Specs Context

The following sections contain the interpretation guides you MUST apply when \
analysing the data. Do not ignore them — they encode domain-specific knowledge \
that pure number comparison cannot capture.

"""

SYSTEM_PROMPT_OUTPUT_FORMAT = """
---

## Required Output Format

Produce EXACTLY the following markdown structure. Do not add extra top-level \
sections. Each section should contain substantive analysis grounded in the \
actual numbers from the data — do not use placeholders.

```markdown
# AI-Driven Performance Analysis: CEL vs Akamai

> Generated by Claude {model} on {timestamp}
> Run: {run_name} | Duration: {duration} | Event limit: {event_limit}

## Executive Verdict
[2–3 sentences: overall winner (if clear), most significant finding, \
and one concrete recommendation]

## Throughput Analysis
[EPS comparison from monitoring logs vs events_published from /inputs/. \
Note any discrepancy and explain it. Comment on whether both inputs \
exhausted the event_limit capacity or left events on the API.]

## Latency Deep Dive
[Compare http_round_trip_time (shared, apples-to-apples), batch_processing_time \
(shared — pipeline ACK latency), cel_processing_time (CEL only) vs \
response_latency (Akamai only). Explain what each difference reveals about \
WHERE time is spent in each input implementation.]

## Memory and CPU Analysis
[GC overhead % from CPU pprof — is it above the 20% threshold? \
JSON decode vs CEL boundary cost breakdown. RSS and alloc trajectory. \
Whether heap growth suggests a leak or normal GC behaviour.]

## pprof Interpretation
[Top CPU functions explained in operational context. Heap growth diff: \
which allocations grew and why. Block/mutex contention — is it \
internal pipeline pressure or external backpressure? Apply the \
indicators from the PPROF_ANALYSIS.md specs.]

## Akamai Reliability Assessment
[offset_expired, hmac_refresh, cursor_drops, api_400_fatal counts. \
Do any non-zero values indicate environmental issues (clock skew, \
API server instability) that may bias the comparison? \
Worker utilization interpretation.]

## Root Cause Hypotheses
[Numbered ranked list. Each hypothesis: one sentence stating the cause, \
one sentence citing the supporting evidence from the data.]

## Recommendations
[Numbered ranked list. Immediate actions first, then config tuning, \
then architectural considerations. Be specific — name the parameter \
or field to change and the expected effect.]

## Suggested Follow-up Tests
[2–3 specific `./bin/run_tests.sh` invocations with flags and one-line \
rationale for each. Focus on tests that would confirm or refute the \
top hypotheses.]
```
"""


def _read_spec(suite_dir: Path, relative_path: str) -> str:
    """Read a spec file. Returns its content or a warning string if missing."""
    p = suite_dir / relative_path
    if p.exists():
        return p.read_text(encoding="utf-8")
    return f"[{relative_path} not found]"


def _read_data_file(run_dir: Path, relative_path: str) -> Optional[str]:
    """Read a data file. Returns None if missing."""
    p = run_dir / relative_path
    if not p.exists():
        return None
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return None


def _build_system_prompt(suite_dir: Path) -> str:
    parts = [SYSTEM_PROMPT_HEADER]
    for spec_path in SPECS_FILES:
        content = _read_spec(suite_dir, spec_path)
        parts.append(f"### {spec_path}\n\n{content}\n\n---\n")
    parts.append(SYSTEM_PROMPT_OUTPUT_FORMAT)
    return "".join(parts)


def _build_user_message(run_dir: Path, run_config: Dict[str, Any]) -> str:
    params = run_config.get("parameters", {})
    run_name = run_config.get("run_name", "unknown")

    lines = [
        f"## Test Run Metadata\n",
        f"- Run name: {run_name}",
        f"- Duration: {params.get('duration', 'N/A')}",
        f"- Interval: {params.get('interval', 'N/A')}",
        f"- Initial interval: {params.get('initial_interval', 'N/A')}",
        f"- Event limit: {params.get('event_limit', 'N/A')}",
        f"- Akamai workers: {params.get('akamai_workers', 'N/A')}",
        f"- Akamai batch size: {params.get('akamai_batch_size', 'N/A')}",
        "",
        "## Input Files\n",
    ]

    for rel_path, description in DATA_FILES:
        content = _read_data_file(run_dir, rel_path)
        if content is None:
            lines.append(f"### FILE: {rel_path} ({description})\n_[File not found — skipped]_\n")
        else:
            # Truncate very large files to avoid hitting context limits
            if len(content) > 50_000:
                content = content[:50_000] + "\n\n[... truncated at 50,000 chars ...]"
            lines.append(f"### FILE: {rel_path} ({description})\n\n```\n{content}\n```\n")

    lines.append(
        "\nPlease analyse the data above and produce the `final_analysis.md` content "
        "following the exact format specified in the system prompt."
    )

    return "\n".join(lines)


def _build_output_header(run_config: Dict[str, Any]) -> str:
    """Build the metadata header to prepend to the AI response."""
    params = run_config.get("parameters", {})
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    run_name = run_config.get("run_name", "unknown")
    # Replace template placeholders in the AI response header section
    return (
        f"<!-- Generated by Claude {MODEL} on {now} | "
        f"Run: {run_name} | "
        f"Duration: {params.get('duration', 'N/A')} | "
        f"Event limit: {params.get('event_limit', 'N/A')} -->\n\n"
    )


def run_ai_analysis(
    run_dir: Path,
    run_config: Dict[str, Any],
    output_dir: Optional[Path] = None,
) -> Path:
    """
    Run AI analysis on a completed test run and write final_analysis.md.

    Args:
        run_dir:    Path to the parent run directory (e.g. runs/my-run/)
        run_config: Parsed run_config.json
        output_dir: Where to write final_analysis.md (default: run_dir/comparison/)

    Returns:
        Path to the written final_analysis.md

    Raises:
        EnvironmentError: If ANTHROPIC_API_KEY is not set
        ImportError: If the anthropic package is not installed
    """
    if anthropic is None:
        raise ImportError(
            "The 'anthropic' package is not installed. "
            "Run: pip install anthropic>=0.40.0"
        )

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "ANTHROPIC_API_KEY environment variable is not set. "
            "Export it before running AI analysis:\n"
            "  export ANTHROPIC_API_KEY=sk-ant-..."
        )

    if output_dir is None:
        output_dir = run_dir / "comparison"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Suite root is two levels up from run_dir (runs/<name>/ -> akamai-test/)
    suite_dir = run_dir.parent.parent

    print(f"  Building prompt from specs in {suite_dir}/specs/")
    system_prompt = _build_system_prompt(suite_dir)
    user_message = _build_user_message(run_dir, run_config)

    print(f"  Calling Claude {MODEL} (this may take up to 60 seconds)...")
    client = anthropic.Anthropic(api_key=api_key)

    message = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )

    response_text = message.content[0].text if message.content else ""
    if not response_text:
        raise RuntimeError("Claude returned an empty response")

    # Prepend a metadata comment and write the output
    output_content = _build_output_header(run_config) + response_text
    output_path = output_dir / OUTPUT_FILENAME
    output_path.write_text(output_content, encoding="utf-8")

    return output_path
